### ISSUE TITLE
Incorrect identification of tokens added and removed when using SegmentMatcher diffstate. 

### ISSUE THREAD

**Issue by groceryheist** [mediawiki-utilities/mwperistence#6]
So far, the best minimal working example I have uses three wikipedia edits. Here is the diff of the third edit, where the incorrect results are observed. https://en.wikipedia.org/w/index.php?title=The_Amazing_Race_16&diff=prev&oldid=402436936

Here is an xml file with the data [persistence-test.tar.gz](https://github.com/mediawiki-utilities/python-mwpersistence/files/2351040/persistence-test.tar.gz)

    from mwxml import Dump
    import deltas
    from deltas.tokenizers import wikitext_split
    from mwpersistence import DiffState

    state = DiffState(deltas.SegmentMatcher(tokenizer=wikitext_split), revert_radius=7)
    xml = Dump.from_file("persistence-test.xml")

    for page in xml:
        for rev in page:
            state_tokens, added, removed = state.update(rev.text, revision=rev.id)

            tokenizer_tokens = wikitext_split.tokenize(rev.text)
            print(rev.id)

           if rev.id == 402436936:
                print([str(t) for t in added])
                ### expected:
                ### ['(', 'of', 'Dan', 'and', 'Jordan' , ')']

                ### found:
                ### ['instead', ' ', 'of', ' ', 'taking', ' ', 'the', ' ', '[[', 'funicular']

In this case I also observe #4 and I suspect that these may be the same bug and have the same root cause, which I believe is probably an issue in github.com/halfak/deltas related to the DiffEngine logic in the segment matcher. So far I haven't build a working example for the deltas bug.

**Comment by halfak** [comment]
I've replicated the issue in deltas and am working on providing a minimal test showing the issue.

**Comment by halfak** [comment]
Wow.  Weird issue.  If I delete most of the article (except for the bits that changed and are mistakenly grabbed as changing) the issue doesn't exist.  Looks like there's something weird in this article that is throwing the algorithm off.  Good find.  If I can ask, how did you find it?  If you just stumbled across this, it might be common, but if you found it algorithmically, maybe it's unusual.

**Comment by halfak** [comment]
Aha!  Got it.  It turns out the segmenter wasn't handling tables correctly.  I've fixed the issue in https://github.com/halfak/deltas/commit/aa314c89b1034263cdd010b976d9d9bce1baff35 and I just uploaded deltas==0.4.7 to pypi with the fix.

**Comment by kayleachampion** [comment]
FWIW, I was the one who found the issue that @groceryheist did the legwork to describe above -- I was looking at the top tokenrevs in a sample of anonymous edits. The first 3 all seemed like mundane edits with fairly modest visible impact, so I started asking questions as to why these would be the most extreme values :). Glad it was a quick find!

**Comment by groceryheist** [comment]
For some more context, I was updating one of our research tools to use the latest versions of mediawiki-utilities, including adding support segment matching based persistence measures.  "Tokenrevs" is our name for a persistent token revisions variable.  I computed this persistence measure for all mainspace edits to en-wiki, which Kaylea was using in a downstream project that looks at a sample of (probably unusual) edits.  She was spot-checking the persistence measure by inspecting outliers.  She saw some discrepancies right away and I tracked them down.

**Comment by groceryheist** [comment]
Thank you Halfak for fixing this so quickly!

**Comment by halfak** [comment]
No problem.  Thank you both for your work finding it.  With your work and mine, we all have better utilities we can share :)

**Comment by groceryheist** [comment]
Yay! :) :+1:

**Comment by groceryheist** [comment]
We checked the fix on a few more cases we identified in the spot check and everything looks good.
