### ISSUE TITLE
New/Old? issue with token persistence incorrect in some cases

### ISSUE THREAD

**Issue by kayleachampion** [mediawiki-utilities/mwperistence#7]
This issue is similar to #6 -- mwpersistence algorithm seems to identify token persistence incorrectly in some cases. I'm spotchecking extreme values as in issue #6, and found a problem in the results of assessing persistence of revision id 535831489, pageid 37562192. This revision was reverted by the very next edit, which is 535831549. However, the persistence delta reports 0 added and 0 removed for this edit, rather than catching that the revert has removed all the tokens added by the previous revision. The situation is visible at 
https://en.wikipedia.org/w/index.php?title=Khurshid_of_Tabaristan&diff=prev&oldid=535831549

Apologies for any incoherence in this report, but perhaps if you can compare persistence outputs for this page id you'll see the issue, or perhaps my colleague @groceryheist can clarify my explanation.

Here's his code snippet we're using to call the API so that we can see where the deltas are wrong -- 
````
#!/usr/bin/env python3
  
import requests
from pprint import pprint
import mwpersistence
import deltas
from mwreverts.defaults import RADIUS
from deltas.tokenizers.wikitext_split import wikitext_split
page_id = 37562192
rev_prev = 535338083
state = mwpersistence.DiffState(deltas.SegmentMatcher(tokenizer=wikitext_split),
                                revert_radius=RADIUS)
params = {'pageids': page_id, 'action': 'query', 'prop': 'revisions',
          'rvprop': 'content|ids|timestamp|sha1|comment|flags|user|userid',
          'rvlimit': 11, 'format': 'json', 'rvstartid': rev_prev,'rvdir':'newer'}

result = requests.get(url='https://en.wikipedia.org/w/api.php', params=params).json()
_, page = result['query']['pages'].popitem()
for rev in page.get('revisions', []):
    text = rev.get('*', '')
    text = text.lower()
    print(rev['revid'])
    current_tokens, tokens_added, tokens_removed = state.update(text, revision=rev["revid"])
    tokens = wikitext_split.tokenize(text)
    if rev['revid'] != rev_prev:
        print(len(tokens_added))
        print(len(tokens_removed))
        print([str(t) for t in tokens_added])
        print([str(t) for t in tokens_removed])
````

@groceryheist edit: formatting.

**Comment by groceryheist** [comment]
By the way, this is with deltas 0.4.7.

**Comment by halfak** [comment]
This is by design.  Reverts don't add/remove tokens.  They instead just restore old tokens to a previous state.  You'll find that the tokens in "current_tokens" reflects the full history of these reverted-to tokens.

See section 4.1.3 in http://reidster.net/pubs/group282-priedhorsky.pdf  "Dealing with Reverts"

See also section 3.1 in https://www-users.cs.umn.edu/~halfaker/publications/A_Jury_of_Your_Peers/halfaker09jury-personal.pdf "Estimating the quality of a contribution"

**Comment by groceryheist** [comment]
I see. We should not be giving credit for tokens added by a revert. But we also want to make sure that people do not get credit when their edits are reverted.  

I assume `diffs2persistence` function do the right thing and that we should probably migrate from using state objects directly to calling `diffstopersistence` for each of our pages.

**Comment by halfak** [comment]
Right, so if you process a set of revisions and you track the words added then those words won't include revision metadata for the revisions they were reverted in (and subsequent revisions unless someone reverts them back in)
